"""Framework- and persistence-independent MCP bridge contracts."""

from .downstream import (
    BridgeDownstreamServer,
    McpSessionBroker,
    McpTransportSession,
    create_mcp_asgi_app,
)
from .engine import BridgeEngine, BridgeSession
from .contracts import (
    BindingPlan,
    BindingAvailabilityStatus,
    BindingAvailabilityChanged,
    BridgeCapabilities,
    BridgeErrorRaised,
    BridgeFailure,
    BridgeFailureCode,
    BridgeObservation,
    BridgeSessionStarted,
    ResourceRead,
    ReadResourceResult,
    ResourceContent,
    ResourceDescriptor,
    EndpointMode,
    EndpointPlan,
    NoOpBridgeObserver,
    BridgeObserver,
    SseUpstreamConfig,
    StdioUpstreamConfig,
    StreamableHttpUpstreamConfig,
    ToolCallCompleted,
    ToolCallResult,
    ToolCallStarted,
    ToolDescriptor,
    ToolsPublished,
    UpstreamConfig,
    UpstreamIdentity,
)
from .routing import AggregateRouter, McpSessionRouter, PassthroughRouter
from .upstream import (
    DefaultUpstreamClientFactory,
    SseUpstreamClient,
    StdioUpstreamClient,
    StreamableHttpUpstreamClient,
    UpstreamClient,
    UpstreamClientFactory,
    UpstreamRuntime,
    build_upstream_client,
)

__all__ = [
    "AggregateRouter",
    "BindingAvailabilityChanged",
    "BindingAvailabilityStatus",
    "BindingPlan",
    "BridgeCapabilities",
    "BridgeDownstreamServer",
    "BridgeEngine",
    "BridgeErrorRaised",
    "BridgeFailure",
    "BridgeFailureCode",
    "BridgeObservation",
    "BridgeObserver",
    "BridgeSessionStarted",
    "BridgeSession",
    "DefaultUpstreamClientFactory",
    "EndpointMode",
    "EndpointPlan",
    "NoOpBridgeObserver",
    "McpSessionRouter",
    "McpSessionBroker",
    "McpTransportSession",
    "PassthroughRouter",
    "ReadResourceResult",
    "ResourceContent",
    "ResourceDescriptor",
    "ResourceRead",
    "SseUpstreamConfig",
    "SseUpstreamClient",
    "StdioUpstreamConfig",
    "StdioUpstreamClient",
    "StreamableHttpUpstreamConfig",
    "StreamableHttpUpstreamClient",
    "ToolCallCompleted",
    "ToolCallResult",
    "ToolCallStarted",
    "ToolDescriptor",
    "ToolsPublished",
    "UpstreamConfig",
    "UpstreamClient",
    "UpstreamClientFactory",
    "UpstreamIdentity",
    "UpstreamRuntime",
    "build_upstream_client",
    "create_mcp_asgi_app",
]
